http_server:
  address: 127.0.0.1
  port: 8080

database:
  username: postgresusr
  password: 1234
  host: host.docker.internal
  port: 5432
  database: songvutdb

redis:
  host: host.docker.internal
  port: 6379
  database: "0"
  timeout: 30
